version: "3.9"
services:

  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
        - .env

  web:
    build: .
    command: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "30s", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db